# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/debian12"
#  config.vm.box = "ubuntu/jammy64"
# config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.boot_timeout = 1200
  config.vm.hostname = "sgedeb2425"
  config.vm.network "private_network", ip: "192.168.56.5"

# Ver: https://www.vagrantup.com/docs/networking/public_network
#  config.vm.network "public_network", bridge: "enp0s31f6", ip: "192.168.6.17"

#  config.vm.synced_folder "./web", "/var/www/html", owner: "vagrant", group: "www-data", mount_options: ["dmode=775,fmode=664"]
  config.vm.provision "shell", path: "config.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
    v.name = "sgedeb2425"
  end
end
